# Azure OpenAI
# pip install langchain-openai
_target_: langchain_openai.AzureChatOpenAI
azure_deployment: ${oc.env:AZURE_OPENAI_DEPLOYMENT}
azure_endpoint: ${oc.env:AZURE_OPENAI_ENDPOINT}
api_key: ${oc.env:AZURE_OPENAI_API_KEY}
api_version: ${oc.env:AZURE_OPENAI_API_VERSION,2024-12-01-preview}
