_target_: llama_index.embeddings.openai_like.OpenAILikeEmbedding
model_name: ${oc.env:EMBEDDING_MODEL_NAME,bge-m3}
api_base: ${oc.env:EMBEDDING_API_BASE,http://localhost:8000}
api_key: ${oc.env:EMBEDDING_API_KEY,-}
